# Generated by Django 4.1.7 on 2023-04-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_alter_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category'),
        ),
    ]
