# Generated by Django 4.1.7 on 2023-04-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='address',
            field=models.CharField(blank=True, default='no address yet', max_length=255, null=True),
        ),
    ]
